baseURL = "/"
languageCode = "en-us"
title = "Belmont-MA.info"
theme = "ghostwriter"
googleAnalytics = "UA-192087749-1"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Information and analysis about Belmont, MA"
    description = "Jason Ketola - Town Meeting Member, Precinct 3"
    github = "https://github.com/jasonketola"
    email = "jasonketola@gmail.com"
    opengraph = true
    rss = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
